# Site settings
title: "Jooeun Lee — Portfolio"
description: "AI · Computer Vision · NLP"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jooeun Lee"
resume_title:                   "AI Research & Development (Undergraduate, INU)"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "너의메일@inu.ac.kr"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "010-9180-0072"
resume_contact_address:         "Incheon, South Korea"

resume_header_contact_info:     "Incheon National University • dlwndms0072@inu.ac.kr"
display_header_contact_info:    "true"

resume_header_intro: "<p>Undergraduate researcher in AI and Computer Science at Incheon National University. My research interests include AI, Computer Vision, Natural Language Processing, Deepfake Detection, and Autonomous Driving. Experienced in building machine learning models and participating in competitions such as LG Aimers and DFCC.</p>"

# Looking for opportunities?
resume_looking_for_work:        "yes"

# Sections
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true

# Resume social links
resume_social_links:
  resume_github_url:            "https://github.com/dlwndms3928"
  # resume_twitter_url:          
  # resume_dribbble_url:         
  # resume_facebook_url:         
  # resume_instagram_url:        
  resume_linkedin_url:          ""   # 없으면 비워두기
  resume_website_url:           "https://dlwndms0072.tistory.com/"
  resume_medium_url:            ""   # 필요 없으면 비우기
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
